<ul class="files" id="Files<?php echo $log->id ?>">
  <?php foreach ($files as $file): ?>
    <li class="<?php echo $file->action ?>-action" title="">
      <?php echo $file->action ?>
      <?php echo $file->file_path ?>
      <?php if ($file->copyfrom_rev): ?>
        (Copy from: <?php echo $file->copyfrom_path ?>@<a href="rev.php?revision=<?php echo $file->copyfrom_rev ?>&amp;repo=<?php echo $repo ?>"><?php echo $file->copyfrom_rev ?></a>)
      <?php endif ?>
      <?php if ($file->action == 'M' && $file->kind == 'file'): ?>
        <a class="control" href="diff.php?repo=<?php echo htmlentities($repo) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">diff</a>
        <a class="control" href="blame.php?repo=<?php echo htmlentities($repo) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">blame</a>
      <?php endif ?>
    </li>
  <?php endforeach ?>
</ul>
