
<!-- 头部 -->
<div id="header">
  <h1>SVN Log Search <?php echo $repo ?></h1>
</div>
<!-- /头部 -->

<!-- 主内容区 -->
<div id="section">
  <form id="SearchForm">
    <div class="search-form">
      <label>
        <input name="keyword" type="text" placeholder="type to search" value="<?php echo $keyword ?>">
        <input type="submit" value="搜索">
      </label>
    </div>
  </form>
  <hr>
  <div id="LogsWrapper">
    <?php include 'template/logs.phtml' ?>
  </div>
</div>
<!-- /主内容区 -->
<script type="text/javascript">
$(function () {
  $('#SearchForm input').keyup(function (ret) {
    var keyword = $('input[name=keyword]').val();
    var data = {keyword: keyword};
    $.get('?', data, function (ret) {
      $('#LogsWrapper').html(ret);
    }, 'html');
  });
});
</script>
