<?php if (isset($logs)): ?>

  <?php if ($count == count($logs)): ?>
    <div><?php echo $count ?> match.</div>
  <?php else: ?>
    <div><?php echo $count ?> match, <?php echo count($logs) ?> show.</div>
  <?php endif ?>

<ul>
  <?php foreach ($logs as $log): ?>
    <li>
      <div class="svn-log-entry">
        <a href="rev.php?revision=<?php echo $log->rev ?>&amp;repo=<?php echo $root_url ?>" class="revision"><?php echo $log->rev ?></a> |
        <a href="author.php?author=<?php echo $log->author ?>&amp;repo=<?php echo $root_url ?>" class="author"><?php echo highlight_keyword($log->author, $keywords) ?></a> |
        <date><?php echo highlight_keyword($log->commit_date, $keywords) ?></date>
        <div class="msg"><?php echo nl2br(highlight_keyword($log->msg, $keywords)) ?></div>
        <ul class="files">
          <?php foreach (get_files_by_rev($log->id) as $file): ?>
            <li class="<?php echo $file->action ?>-action">
              <?php echo $file->action ?>
              <?php echo highlight_keyword($file->file_path, $keywords) ?>
              <?php if ($file->action == 'M' && $file->kind == 'file'): ?>
                <a class="control" href="diff.php?repo=<?php echo htmlentities($root_url) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">diff</a>
                <a class="control" href="blame.php?repo=<?php echo htmlentities($root_url) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">blame</a>
              <?php endif ?>
            </li>
          <?php endforeach ?>
        </ul>
      </div>
    </li>
  <?php endforeach ?>
</ul>
<?php endif ?>
