<?php if (isset($logs)): ?>

  <?php if ($count == count($logs)): ?>
    <div><?php echo $count ?> match.</div>
  <?php else: ?>
    <div><?php echo $count ?> match, <?php echo count($logs) ?> show.</div>
  <?php endif ?>

<ul>
  <?php foreach ($logs as $log): ?>
    <li>
      <div class="svn-log-entry">
        <a href="rev.php?revision=<?php echo $log->rev ?>&amp;repo=<?php echo $root_url ?>" class="revision"><?php echo $log->rev ?></a> |
        <a href="author.php?author=<?php echo $log->author ?>&amp;repo=<?php echo $root_url ?>" class="author"><?php echo highlight_keyword($log->author, $keywords) ?></a> |
        <date><?php echo highlight_keyword($log->commit_date, $keywords) ?></date>
        <div class="msg"><?php echo nl2br(highlight_keyword($log->msg, $keywords)) ?></div>
        <?php include 'files.phtml' ?>
      </div>
    </li>
  <?php endforeach ?>
</ul>
<?php endif ?>
