
<!-- 头部 -->
<div id="header">
  <h1><?php echo $title ?></h1>
</div>
<!-- /头部 -->

<!-- 主内容区 -->
<div id="section">
  <div class="svn-log-entry">
    <span class="revision"><?php echo $log->rev ?></span> |
    <name><?php echo $log->author ?></name> |
    <date><?php echo $log->commit_date ?></date>
    <div class="msg"><?php echo nl2br($log->msg) ?></div>
    <?php render('files.phtml', array(
      'files' => $files = get_files_by_rev($log->id),
      'log' => $log,
      'repo' => $repo,
    )) ?>
  </div>
</div>
<!-- /主内容区 -->
