
<!-- 头部 -->
<div id="header">
  <h1><?php echo $title ?></h1>
</div>
<!-- /头部 -->

<!-- 主内容区 -->
<div id="section">
  <div class="svn-log-entry">
    <span class="revision"><?php echo $log->rev ?></span> |
    <name><?php echo $log->author ?></name> |
    <date><?php echo $log->commit_date ?></date>
    <div class="msg"><?php echo nl2br($log->msg) ?></div>
    <ul class="files">
      <?php foreach (get_files_by_rev($log->id) as $file): ?>
        <li class="<?php echo $file->action ?>-action">
          <?php echo $file->action ?>
          <?php echo $file->file_path ?>
          <?php if ($file->action == 'M' && $file->kind == 'file'): ?>
            <a class="control" href="diff.php?repo=<?php echo htmlentities($root_url) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">diff</a>
            <a class="control" href="blame.php?repo=<?php echo htmlentities($root_url) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">blame</a>
          <?php endif ?>
        </li>
      <?php endforeach ?>
    </ul>
  </div>
</div>
<!-- /主内容区 -->
