
<!-- 头部 -->
<div id="header">
  <h1>SVN Log Search</h1>
  <div><?php echo $root_url ?></div>
</div>
<!-- /头部 -->

<!-- 主内容区 -->
<div id="section">
  <form>
    <div>
      <label>
        <input name="keyword" placeholder="key word" value="<?php echo $keyword ?>">
        <input type="submit" value="搜索">
      </label>
    </div>
  </form>
  <hr>
  <div>
    <?php if (isset($logs)): ?>
    <div><?php echo count($logs) ?> Matched.</div>
    <ul>
      <?php foreach ($logs as $log): ?>
        <li>
          <div class="svn-log-entry">
            <rev><?php echo $log->rev ?></rev> |
            <name><?php echo $log->author ?></name> |
            <date><?php echo $log->commit_date ?></date>
            <ul>
              <?php foreach (get_files_by_rev($log->id) as $file): ?>
                <li class="<?php echo $file->action ?>-action">
                  <?php echo $file->action ?>
                  <?php echo $file->file_path ?>
                  <?php if ($file->action == 'M'): ?>
                    <a href="diff.php?repo=<?php echo htmlentities($root_url) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">diff</a>
                    <a href="blame.php?repo=<?php echo htmlentities($root_url) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">blame</a>
                  <?php endif ?>
                </li>
              <?php endforeach ?>
            </ul>
            <div><?php echo nl2br($log->msg) ?></div>
          </div>
        </li>
      <?php endforeach ?>
    </ul>
    <?php endif ?>
  </div>
</div>
<!-- /主内容区 -->
