
<!-- 头部 -->
<div id="header">
  <h1>SVN Log Search</h1>
  <h2><?php echo $root_url ?></h2>
</div>
<!-- /头部 -->

<!-- 主内容区 -->
<div id="section">
  <form>
    <div class="search-form">
      <label>
        <input name="keyword" type="text" placeholder="type to search" value="<?php echo $keyword ?>">
        <input type="submit" value="搜索">
      </label>
    </div>
  </form>
  <hr>
  <div>
    <?php if (isset($logs)): ?>
    <div><?php echo count($logs) ?> Matched.</div>
    <ul>
      <?php foreach ($logs as $log): ?>
        <li>
          <div class="svn-log-entry">
            <rev><?php echo $log->rev ?></rev> |
            <name><?php echo $log->author ?></name> |
            <date><?php echo $log->commit_date ?></date>
            <div class="msg"><?php echo nl2br(highlight_keyword($log->msg, $keywords)) ?></div>
            <ul class="files">
              <?php foreach (get_files_by_rev($log->id) as $file): ?>
                <li class="<?php echo $file->action ?>-action">
                  <?php echo $file->action ?>
                  <?php echo highlight_keyword($file->file_path, $keywords) ?>
                  <?php if ($file->action == 'M'): ?>
                    <a class="control" href="diff.php?repo=<?php echo htmlentities($root_url) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">diff</a>
                    <a class="control" href="blame.php?repo=<?php echo htmlentities($root_url) ?>&amp;file=<?php echo $file->file_path ?>&amp;revision=<?php echo $log->rev ?>">blame</a>
                  <?php endif ?>
                </li>
              <?php endforeach ?>
            </ul>
          </div>
        </li>
      <?php endforeach ?>
    </ul>
    <?php endif ?>
  </div>
</div>
<!-- /主内容区 -->
