<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title><?php echo $title ?></title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="css/typo.css">
  <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
  <?php include $tpl ?>
</body>
</html>


